# Generated by Django 4.1.4 on 2023-02-11 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_category_remove_product_image_product_image_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='categoryName',
            new_name='category_name',
        ),
    ]
